### ISSUE TITLE
week2_exercise.html?

### ISSUE THREAD

**Issue by ratnanil** [zimmewen/cma_week2#1]
Hey Wenke!

Your repo is looking good! We will take a closer look in the next few days. In the meantime, can you also push week2_exercise.html to your repo? If you haven't created this file yet, you can do so by "knitting" week2_exercise.Rmd.

See you in the exercise soon!

Nils

**Comment by zimmewen** [comment]
Hey Nils
I did as you said, so you can find the html in my repo.
LG
