### ISSUE TITLE
Html file?

### ISSUE THREAD

**Issue by ratnanil** [zimmewen/cma_week2#2]
I see there is no 'html' file in your repo. In case you are working with Rmarkdown, creating an html file is very simple. Simpliy 'render' the document using the 'Render' Button or the keyboard shortcut <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>K</kbd>\n\n PS: This issue was generated automatically.

**Comment by zimmewen** [comment]
I'm sorry, I don't understand. Last week I received the same issue, that's why I produced an html-file, which I uploaded here. I can see this file in my repo.

**Comment by ratnanil** [comment]
Sorry, this issue was created automatically and by mistake. You can ignore it!
