### ISSUE TITLE
Remove verbose messages from your output html

### ISSUE THREAD

**Issue by ratnanil** [zimmewen/cma_week2#3]
Just some cosmetics: You can add the option `message = FALSE` to remove all verbose messages in the output html.

To do so, replace this line

https://github.com/zimmewen/cma_week2/blob/06467d7496aa66c30010bb31c98ff040cfe38f31/week2_exercise.Rmd#L14

with this:

```
{r message = FALSE}
```

**Comment by zimmewen** [comment]
I tried, but get an error when I want to produce the html-file. We might check this together on friday.

**Comment by ratnanil** [comment]
Let's do that!

**Comment by zimmewen** [comment]
Solved during class. Thanks.
